spring:
  application:
    name: excelImporter
  datasource:
    url: jdbc:mysql://localhost:3306/test?user=root&password=040424&useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9001
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

